networks:
  app-network:
    driver: bridge

services:
  db:
    image: redis:latest
    environment:
      REDIS_DB: 0
      REDIS_PORT: 6379
      REDIS_HOST: localhost
      REDIS_PASSWORD: 1234
    ports:
      - "${DB_PORT}:6379"
    networks:
      app-network:

  app:
    image: trisend:latest 
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}

      HOST: ${HOST}
      PORT: ${PORT}
      APP_ENV: ${APP_ENV}

      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}

      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_USERNAME: ${SMTP_USERNAME}
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      app-network:
    depends_on:
      - db
